[project]
name = "balkon_kino"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django",
    "django-rest-framework",
    "django-split-settings",
    "fastapi>=0.136.3",
    "flask",
    "pwdlib>=0.3.0",
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.13.0",
    "requests",
    "uvicorn>=0.48.0",
]
