# Generated by Django 6.0.3 on 2026-03-27 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0003_watchlist_created_at_alter_watchlist_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
